### ISSUE TITLE
ERROR: quant_cuda-0.0.0-cp38-cp38-win_amd64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by akdcelcopr77** [0cc4m/KoboldAI#13]
when i install by the cmd, i got the error: ERROR: quant_cuda-0.0.0-cp38-cp38-win_amd64.whl is not a supported wheel on this platform.

and some notice:  A new release of pip is available: 23.0.1 -> 23.1.1
 To update, run: python.exe -m pip install --upgrade pip

thanks.

**Comment by akdcelcopr77** [comment]
may be i have solve it by conda create an env in which python=3.8.
hope that this can hlep others. 
good luck.

**Comment by 0cc4m** [comment]
Yes, you do need Python 3.8 to use the wheel, otherwise you have to compile it yourself.
