### ISSUE TITLE
pt not found

### ISSUE THREAD

**Issue by olamedia** [0cc4m/KoboldAI#16]
At the start of `def prepare_4bit_load` in `aiserver.py`
It expects pt file to start with `4bit*`, while most of the models have `*-4bit-*` at the middle, may be it is better to replace

```python
paths_4bit = ["4bit*.safetensors", "4bit*.pt"]
```
with
```python
paths_4bit = ["*4bit*.safetensors", "*4bit*.pt"]
```

**Comment by olamedia** [comment]
(and modifying regexp to find group size `g = re.findall("^(?:4bit)(?:-)(\d+)(?:g-?)", fname)`)

**Comment by 0cc4m** [comment]
Yes, that would be better, but we'll move to a better model format soon anyways, which conforms to Huggingface standards.
