### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by conradcn** [0cc4m/KoboldAI#21]
Hey!

I followed the instructions and set up the model from [here](https://huggingface.co/MetaIX/OpenAssistant-Llama-30b-4bit) in the models directory like this, but am getting the following error when loading the model after starting the application with play.bat:
[image](https://user-images.githubusercontent.com/86856874/236523131-42bbf3fc-fe65-4fa0-a7ec-2a35ba2c2e48.png)
![image](https://user-images.githubusercontent.com/86856874/236523705-abd4f4b7-f352-41b1-b907-2631e93a5dbc.png)

I'm guessing I did something wrong, because I also don't see any way to switch to 4-bit in the UI, though I downloaded the files directly from the repo (twice).

Any thoughts?
System is running Windows 10, GPU is an RTX 4090.

Thanks for making this repo! I'm really excited to dive in.

**Comment by 0cc4m** [comment]
Make sure to load the model from UI2 (`Try new UI` button in old UI), it only shows up there.

**Comment by conradcn** [comment]
That did it. Thanks!
