### ISSUE TITLE
ImportError when running "play.sh"

### ISSUE THREAD

**Issue by brendan-donohoe** [0cc4m/KoboldAI#22]
Hello! I seem to be running into an import error with the latest version of the code.  When installing Kobold via install_requirements.sh and running play.sh, it gives me a message that ansi2html cannot be found.  After I used commandline.sh to hop into the environment and pip install it manually, I got another importerror mentioning that transformers cannot be found.  It looks like the Python packages aren't being installed into the environment, and I'm wondering if this has something to do with the most recent change to install_requirements.sh.  This approach worked with previous versions of the repo (as of last running it a couple of days ago).

**Comment by 0cc4m** [comment]
Yeah, I accidentally uploaded a change to install_requirements, sorry. Should be fixed now.
