### ISSUE TITLE
No 4-bit toggle

### ISSUE THREAD

**Issue by Magnaderra** [0cc4m/KoboldAI#23]
Hi!
I install Pygmalion with this [guide](https://docs.alpindale.dev/local-installation-(gpu)/koboldai4bit/) and I have not  4-bit toggle. Is it a bug? What I do wrong?

**Comment by 0cc4m** [comment]
The 4-bit toggle has recently been removed. But if it is a 4-bit model (for example `4bit-128g.safetensors` file exists) then it will load as 4-bit.

**Comment by Magnaderra** [comment]
Okay, no problem then) Thank you!
