### ISSUE TITLE
Loading a model via command line (--model) does not work in 0cc4m Branch

### ISSUE THREAD

**Issue by RandomBanana122132** [0cc4m/KoboldAI#27]
Discussed briefly in Discord:

**Issue:** When using the `--model` command with play.bat, the following error is thrown (both 4bit and non-4bit models):
![image](https://github.com/0cc4m/KoboldAI/assets/133126626/234e988e-a91f-430e-8fe0-579256d90d99)

Performing the same action `play.bat --model "PygmalionAI_pygmalion-6b" --no_ui` in United loads correctly as expected.

![image](https://github.com/0cc4m/KoboldAI/assets/133126626/40469174-986d-496a-8399-bc2b29608b2d)

**Comment by 0cc4m** [comment]
Can you retest? I think I fixed it.

**Comment by RandomBanana122132** [comment]
@0cc4m  sorry for the delay, missed this message. Tested and confirmed it now works - is there a way/expectation to load it with a 4bit model, or is the expectation that it'll only work the same as United? Right now, parity with United, can't seem to load a 4bit model.

**Comment by 0cc4m** [comment]
@RandomBanana122132 There is still some issue with just using model, but 4bit loading from terminal works for me if I use `./play.sh --host --model wizardLM-7B-GPTQ --path models/wizardLM-7B-GPTQ` for example. Can you test if that also works for you? That's at least a workaround.

**Comment by Tmichala** [comment]
> @RandomBanana122132 There is still some issue with just using model, but 4bit loading from terminal works for me if I use `./play.sh --host --model wizardLM-7B-GPTQ --path models/wizardLM-7B-GPTQ` for example. Can you test if that also works for you? That's at least a workaround.

Not that guy, but the error I was getting before was "OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory models\llama-30b-4bit."

I can confirm that adding both the --model and --path arguments works for me on Windows.

**Comment by RandomBanana122132** [comment]
> @RandomBanana122132 There is still some issue with just using model, but 4bit loading from terminal works for me if I use `./play.sh --host --model wizardLM-7B-GPTQ --path models/wizardLM-7B-GPTQ` for example. Can you test if that also works for you? That's at least a workaround.

Much appreciated, looks like this works for me. Thank you for looking into this and getting it sorted :) I'll close this off as fixed!
