### ISSUE TITLE
Error using previously good model.

### ISSUE THREAD

**Issue by HeroMines** [0cc4m/KoboldAI#30]
OS: Windows 10
CPU: AMD Ryzen 5 5600 
GPU: RTX 3060 12 GB
RAM: 16 GB

Trying to load [WizardLM-7B](https://mega.nz/folder/IeUgUbaZ#C8Ng-81-DAV_qfWqbVMoEw/folder/ZH9hjbiC), which worked just fine a few days ago no longer works with this new update. It keeps giving an "There is no item named '4bit-128g/data/0' in the archive" error.

Known Good commit hash: https://github.com/0cc4m/KoboldAI/commit/4180620999307a8eefb2bcd05e94161eb478243b
Bad commit hash: https://github.com/0cc4m/KoboldAI/commit/a2d01bb9e454a0c951fc9c4c3e67599bcf188b5b

Full Error MSG:
https://pastebin.com/SXUv3hJb

**Comment by henk717** [comment]
Should be fixed now, you can try again.

**Comment by HeroMines** [comment]
> Should be fixed now, you can try again.

Confirmed to be working. Thank you all.
