### ISSUE TITLE
Cannot find the path specified & No module named 'hf_bleeding_edge' when trying to start.

### ISSUE THREAD

**Issue by TheFairyMan** [0cc4m/KoboldAI#41]
Hello, first time trying out this branch, while normal KoboldAI works and so does ooabooga, this one I'm getting some errors that I have no idea what they could be nor how to fix it.

Everything has been installed as per usual, Windows 10 user.

This si the error I get when opening the "play.bat" to start the server:

```
The system cannot find the file specified.
Runtime launching in B: drive mode
The system cannot find the path specified.
Colab Check: False, TPU: False
Traceback (most recent call last):
  File "C:\Users\TheFairyMan\OneDrive\Documentos\AI-DIFFUSIONS\KoboldAI\aiserver.py", line 604, in <module>
    from modeling.inference_models.hf_torch_4bit import load_model_gptq_settings
  File "C:\Users\TheFairyMan\OneDrive\Documentos\AI-DIFFUSIONS\KoboldAI\modeling\inference_models\hf_torch_4bit.py", line 12, in <module>
    from transformers import GPTNeoForCausalLM, AutoTokenizer, LlamaTokenizer
ImportError: cannot import name 'LlamaTokenizer' from 'transformers' (C:\Users\TheFairyMan\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\__init__.py)
```

And then it never opens and just cancels, I have no diea which path it's refering to and no idea what to do about the Llama tokenizer problem.

**Comment by BadisG** [comment]
I have the same issue 
It looks like it's not finding the B: drive somehow 

![image](https://github.com/0cc4m/KoboldAI/assets/110173477/06d130a9-3972-464b-83d8-02fe6cd84801)

I think that's because the play.bat is searshing on somewhere that doesn't exists
there is no B:\python\condbin after the installation
![image](https://github.com/0cc4m/KoboldAI/assets/110173477/33f7b2c2-44a8-4d87-9911-810aa742a1ca)

**Comment by TheFairyMan** [comment]
the B drive is a temporary drive it creates upon startup unless you chose the other option (which didn't work for me for the normal KoboldAI client, so that one also sues temp B: Drive), so it's location does exist, unless the files in there doesn't, even attempting to run the play.bat with the B: drive already open, it gives that error

**Comment by BadisG** [comment]
Yeah, B: exists, but B:\python\condbin doesn't, and that's what play.bat is searshing for, and that's the reason we both have the "The system cannot find the file specified"
![image](https://github.com/0cc4m/KoboldAI/assets/110173477/5562bf6a-4dea-4ba9-8e61-0db1e46b4a93)

**Comment by TheFairyMan** [comment]
Ah indeed, seems to be something that is from this version only then, the KoboldAI Client doesn't search for such, nor does that folder exists inside the B drive.
I wonder what we have to install in there to get it to work, or if we have to install it elsewhere inside the KoboldAI folder.

**Comment by BadisG** [comment]
@TheFairyMan I think I found the solution, you have to install everything on powershell, not cmd, and that way you get the condbin folder

**Comment by TheFairyMan** [comment]
> @TheFairyMan I think I found the solution, you have to install everything on powershell, not cmd, and that way you get the condbin folder

Thanks, seems to have progressed a little, but now I get a new error about "hf_leeding_edge" and path not found still.
```
The system cannot find the file specified.
Runtime launching in B: drive mode
The system cannot find the path specified.
Colab Check: False, TPU: False
Traceback (most recent call last):
  File "D:\KoboldAI\aiserver.py", line 604, in <module>
    from modeling.inference_models.hf_torch_4bit import load_model_gptq_settings
  File "D:\KoboldAI\modeling\inference_models\hf_torch_4bit.py", line 13, in <module>
    from hf_bleeding_edge import AutoModelForCausalLM
ModuleNotFoundError: No module named 'hf_bleeding_edge'
```

**Comment by BadisG** [comment]
you should delete everything and then redo everything on the powershell

```
git clone https://github.com/0cc4m/KoboldAI -b latestgptq --recurse-submodules
cd KoboldAI
.\install_requirements.bat
```

**Comment by TheFairyMan** [comment]
Yes, I redid the entire installation from zero.

**Comment by BadisG** [comment]
It's a shame it didn't work for you, I hope you'll find the solution soon, maybe try with the subfolder, to make it work you must have 0 empty space on your path

For example D:/Kobold AI won't work, but D:/KoboldAI would do

**Comment by TheFairyMan** [comment]
Installed everything again and tried the subfodler option, got same error about hf_bbleeding_edge.
My guess si that it's part of a missing module that isn't getting installed, but I have no diea about the proper module's name to install it and see if it works.

**Comment by BadisG** [comment]
> > @TheFairyMan I think I found the solution, you have to install everything on powershell, not cmd, and that way you get the condbin folder
> 
> Thanks, seems to have progressed a little, but now I get a new error about "hf_leeding_edge" and path not found still.
> 
> ```
> The system cannot find the file specified.
> Runtime launching in B: drive mode
> The system cannot find the path specified.
> Colab Check: False, TPU: False
> Traceback (most recent call last):
>   File "D:\KoboldAI\aiserver.py", line 604, in <module>
>     from modeling.inference_models.hf_torch_4bit import load_model_gptq_settings
>   File "D:\KoboldAI\modeling\inference_models\hf_torch_4bit.py", line 13, in <module>
>     from hf_bleeding_edge import AutoModelForCausalLM
> ModuleNotFoundError: No module named 'hf_bleeding_edge'
> ```

The fact you have a Runtime launching in B: drive mode -> The system cannot find the path specified. means you still don't have the condbin folder right?

**Comment by TheFairyMan** [comment]
No, it still wasn't there, thou the subfolder option also gave the "The system cannot find the path specified." error, so it must not e creating it inside whatever subfodler it is using as well.

Did yours create the condbin folder when u ran it through powershell?

**Comment by BadisG** [comment]
Yeah, when I ran the commands through powershell, it magically created the condbin folder, you know what, I can give that to you and you try to see if it works (you put it on the miniconda3 folder)
https://www.dropbox.com/s/7r9sqnln2h7cfco/New%20Archive%20WinRAR%20ZIP.zip?dl=0

**Comment by TheFairyMan** [comment]
> Yeah, when I ran the commands through powershell, it magically created the condbin folder, you know what, I can give that to you and you try to see if it works (you put it on the miniconda3 folder) https://www.dropbox.com/s/7r9sqnln2h7cfco/New%20Archive%20WinRAR%20ZIP.zip?dl=0

Still getting same error about path not found, but seems like it's executing conda because everytime it creates a new folder in B: called "conda-1195" and the last 4 digits are random each time.
but the error is still the same.

**Comment by BadisG** [comment]
This one is for the subfolder, not B: try to see if that changes anything

**Comment by TheFairyMan** [comment]
> This one is for the subfolder, not B: try to see if that changes anything

Oh, sorry for the misunderstanding, i'll try again.

**Comment by TheFairyMan** [comment]
it worked, but new error...
![image](https://github.com/0cc4m/KoboldAI/assets/92614831/91b7948b-f360-4c13-8393-34b6837ebf5a)
also, I can see that it isntalled bleeding edge right aove, no idea why it can't find it.

```
The system cannot find the file specified.
Runtime launching in subfolder mode
'"D:\Large-Language-Models\KoboldAI\umamba.exe"' is not recognized as an internal or external command,
operable program or batch file.
Colab Check: False, TPU: False
Traceback (most recent call last):
  File "D:\KoboldAI\aiserver.py", line 604, in <module>
    from modeling.inference_models.hf_torch_4bit import load_model_gptq_settings
  File "D:\KoboldAI\modeling\inference_models\hf_torch_4bit.py", line 13, in <module>
    from hf_bleeding_edge import AutoModelForCausalLM
ModuleNotFoundError: No module named 'hf_bleeding_edge'
```

**Comment by BadisG** [comment]
I think I just double clicked on play.bat, I'm not using powershell anymore for that

**Comment by TheFairyMan** [comment]
Didn't work either, one of the Koboldai devs said on discord it might be because of my system language, since he saw people in the past with a similar problem and they fixed by changing system language, gonna have to try it later... problem is that ti'll mess up a big part of my pc

EDIT: didn't work, I still get the same error, I tested using English (US) locale and language.

**Comment by TheFairyMan** [comment]
Update, it's working now, one of the KoboldAI devs Henky helped me and was very throughout with it.
Turns out my problem is that I had Conda and Python installed and they were hijacking his own conda and not letting it work.

if you ever typed `conda init`, you botched your system to always hijack it whenever you start a cmd window, to stop it, you need to open Regedit and go to `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor` and look if there is something else in that folder set to initialize the conda and miniconda.

As for the Python hijacking one (which also happens in PowerShell, thus why for me it still wasn't working) it is very complex, I forgot some parts on how to do it and dev helped me by making customized .bat to take care of it, and the dev said he'll try to find a solution for people in this specific case where it'll check if they have a python/conda hijacking the calls and switch them around for the proper one.
Turns out my case was like a 0.001% specific case since I had multiple things hijacking the calls XD

Anyways, I think I can close this thread and thank Henky a lot for his time and help, if anybody finds themselves in the same situation as me, where no matter what you do it never works, and need some help I could try going through what he thought me and see if it works.
