### ISSUE TITLE
ModuleNotFoundError when starting "play.bat"

### ISSUE THREAD

**Issue by anyezhixie** [0cc4m/KoboldAI#44]
Runtime launching in B: drive mode
Traceback (most recent call last):
  File "aiserver.py", line 26, in <module>
    from ansi2html import Ansi2HTMLConverter
ModuleNotFoundError: No module named 'ansi2html'
I am on a window system, tried everything I could find, several reinstalls and still the same, help.
I can't use "install_requirements.sh" to install, I'm using "install_requirements.bat".

**Comment by henk717** [comment]
Try borrowing install_requirements.bat from here and choose to delete the existing files : https://raw.githubusercontent.com/henk717/KoboldAI/united/install_requirements.bat

**Comment by anyezhixie** [comment]
> Try borrowing install_requirements.bat from here and choose to delete the existing files : https://raw.githubusercontent.com/henk717/KoboldAI/united/install_requirements.bat

Thanks, but I found this update before I saw your reply and what I did was you downloaded and replaced all the files of this latest batch of updates, will this affect the 4bit version?

**Comment by anyezhixie** [comment]
@henk717 Hi, I'm still getting the same result after doing this, I took screenshots of several situations that seem to be errors on the way to installing the BAT run, I hope it will help you to judge the situation, please.
https://i.imgloc.com/2023/06/05/VCBZ6o.png
https://i.imgloc.com/2023/06/05/VCpujA.png
https://i.imgloc.com/2023/06/05/VCBiQN.png

**Comment by anyezhixie** [comment]
Thanks to the people who helped me, it finally worked after updating the files and fixing the network problem.
