### ISSUE TITLE
Hey, I'm not sure what's wrong, but it does automatically delete a lot of output at the end of each generation.

### ISSUE THREAD

**Issue by anyezhixie** [0cc4m/KoboldAI#46]
What I have observed so far is that when using models like HyperMantis and Chronos, it will delete all but the first paragraph of the current output after each generation.
When using Erebus and Hermes, it will most likely delete all the content generated this time.
If I switch to the new UI, all the content generated by the latter will probably be saved, but it will not be possible to go backwards, only the commands and actions I entered will be reverted, but not the AI output.
I tried reinstalling KAI to set it back to the initial state, but I had the same problem, which did not occur before with the non-4bit version.

**Comment by 0cc4m** [comment]
Check the formatting options, there's one about trimming sentences. It sounds like that.

**Comment by anyezhixie** [comment]
> Check the formatting options, there's one about trimming sentences. It sounds like that.


Hi, I don't think it's the options that are the problem. It's like in the screenshot, even if I turn off all the relevant options, it still removes all the output, the token shows and the script shows that it does write something, it just gets deleted by itself.
https://imgloc.com/i/VlgByq
https://imgloc.com/i/VlgXIz

**Comment by 0cc4m** [comment]
I can't really help you with that, this fork is only about running 4bit models. The rest of the code comes from henk's united branch. Best ask [over there](https://github.com/henk717/KoboldAI) or on the KoboldAI Discord.

**Comment by anyezhixie** [comment]
> I can't really help you with that, this fork is only about running 4bit models. The rest of the code comes from henk's united branch. Best ask [over there](https://github.com/henk717/KoboldAI) or on the KoboldAI Discord.

Thank you, I'm sorry for bothering you.
