### ISSUE TITLE
cant load models 4bit

### ISSUE THREAD

**Issue by scavru** [0cc4m/KoboldAI#55]
Good afternoon, I have an old version where everything works. 
` 35f908e147fcac121bdafaf7ca4b751d8091f480 unknown <scav@scav.(none)> 1681297611 +0300	clone: from https://github.com/0cc4m/KoboldAI
`
I'm trying to reinstall or clear install, but the models are not loading. errors log

`CUDA SETUP: CUDA runtime path found: D:\KoboldAI\KoboldAI\miniconda3\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary D:\KoboldAI\KoboldAI\miniconda3\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll...
Loading checkpoint shards:   0%|                                                                 | 0/7 [00:00<?, ?it/s]
ERROR      | modeling.inference_models.hf_torch:_get_model:403 - Lazyloader failed, falling back to stock HF load. You may run out of RAM here. Details:
ERROR      | modeling.inference_models.hf_torch:_get_model:404 - [Errno 2] No such file or directory: 'D:\\KoboldAI\\KoboldAI\\models\\MetaIX_Guanaco-33B-4bit\\pytorch_model-00001-of-00007.bin'
ERROR      | modeling.inference_models.hf_torch:_get_model:405 - Traceback (most recent call last):
  File "D:\KoboldAI\KoboldAI\miniconda3\lib\site-packages\transformers\modeling_utils.py", line 463, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "D:\KoboldAI\KoboldAI\modeling\lazy_loader.py", line 523, in torch_load
    model_dict = old_torch_load(
  File "D:\KoboldAI\KoboldAI\miniconda3\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\KoboldAI\KoboldAI\miniconda3\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\KoboldAI\KoboldAI\miniconda3\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\KoboldAI\\KoboldAI\\models\\MetaIX_Guanaco-33B-4bit\\pytorch_model-00001-of-00007.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\KoboldAI\KoboldAI\modeling\inference_models\hf_torch.py", line 393, in _get_model
    model = AutoModelForCausalLM.from_pretrained(
  File "D:\KoboldAI\KoboldAI\miniconda3\lib\site-packages\transformers\models\auto\auto_factory.py", line 484, in from_pretrained
    return model_class.from_pretrained(
  File "D:\KoboldAI\KoboldAI\modeling\patches.py", line 92, in new_from_pretrained
    return old_from_pretrained(
  File "D:\KoboldAI\KoboldAI\miniconda3\lib\site-packages\transformers\modeling_utils.py", line 2881, in from_pretrained
    ) = cls._load_pretrained_model(
  File "D:\KoboldAI\KoboldAI\miniconda3\lib\site-packages\transformers\modeling_utils.py", line 3214, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "D:\KoboldAI\KoboldAI\miniconda3\lib\site-packages\transformers\modeling_utils.py", line 466, in load_state_dict
    with open(checkpoint_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\KoboldAI\\KoboldAI\\models\\MetaIX_Guanaco-33B-4bit\\pytorch_model-00001-of-00007.bin'

INFO       | modeling.inference_models.hf_torch:_get_model:406 - Falling back to stock HF load...
Loading checkpoint shards:   0%|                                                                 | 0/7 [00:00<?, ?it/s]
WARNING    | modeling.inference_models.hf_torch:_get_model:439 - Fell back to GPT2LMHeadModel due to [Errno 2] No such file or directory: 'D:\\KoboldAI\\KoboldAI\\models\\MetaIX_Guanaco-33B-4bit\\pytorch_model-00001-of-00007.bin'
You are using a model of type llama to instantiate a model of type gpt2. This is not supported for all configurations of models and can yield errors.
You are loading your model in 8bit or 4bit but no linear modules were found in your model. this can happen for some architectures such as gpt2 that uses Conv1D instead of Linear layers. Please double check your model architecture, or submit an issue on github if you think this is a bug.`

**Comment by 0cc4m** [comment]
`bitsandbytes` integration isn't developed by me, so I can't help you with issues that come from it. This fork is for GPTQ models. From your log I can tell that it's trying to load a GPTQ model with bitsandbytes in 8 or 4-bits, which isn't possible.

**Comment by scavru** [comment]
This is GPTQ model https://huggingface.co/MetaIX/Guanaco-33B-4bit
this model here works on the version that was downloaded in April, now there are errors.
I've already installed_requirements and updated it, no matter how I try, it doesn't want to work. If you are interested, here is a 7z archive with the version that works https://disk.yandex.ru/d/6xsTrcJ1P-cN1w.
`       DEVICE ID  |  LAYERS  |  DEVICE NAME
               0  |      60  |  NVIDIA GeForce RTX 3090
             N/A  |       0  |  (Disk cache)
             N/A  |       0  |  (CPU)
Using 4-bit file: D:\k\models\MetaIX_Guanaco-33B-4bit\4bit.safetensors, groupsize -1
Trying to load llama model in 4-bit
Loading model ...
Done.`

**Comment by 0cc4m** [comment]
Can you tell me which branch you were using in the first post?

**Comment by scavru** [comment]
I just did another clean install and everything worked.Well, how come
